"""empty message

Revision ID: 456798a88211
Revises: 1e493f5407f2
Create Date: 2020-09-30 23:44:41.710277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456798a88211'
down_revision = '1e493f5407f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
